name: "RaspiNukiBridge"
description: "Nuki bridge to HTTP"
version: "0.0.1"
slug: "raspi_nuki_bridge"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
ports:
  8080/tcp: 8080

