name: "Nuki Bridge"
description: "Nuki Bluetooth to HTTP bridge"
version: "0.0.23"
slug: "nuki_bridge"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8080/tcp: 8080
host_dbus: true